theme: "starter-hugo-academic"
title: Mobina Kashaniyan
baseURL: 'https://iammobina.github.io/'

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

enableGitInfo: false
summaryLength: 50
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  publications: '/publication/:slug/'
  publication: '/publication/:slug/'
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
  blog: '/blog/:slug'

disableAliases: true

outputs:
  home: [HTML, RSS, JSON, WebAppManifest]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart

timeout: 600000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  _merge: deep
  tableofcontents:
    startLevel: 1
    endLevel: 4
    ordered: false

security:
  _merge: deep

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
