main:
  - name: Home
    url: '/index.html'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Education
    url: '#education'
    weight: 40
  - name: Research Experience
    url: '#experience'
    weight: 50
  - name: Projects
    url: '#projects'
    weight: 60
  - name: Teaching
    url: '#teaching'
    weight: 70
  - name: Skills
    url: '#skills'
    weight: 80
  - name: Contact
    url: '#contact'
    weight: 100
